import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, MessageSquareHeart, Send, ShieldCheck, Star } from "lucide-react";
import { useState } from "react";

export default function Community() {
  const { isAuthenticated, user } = useAuth();
  const utils = trpc.useUtils();
  const [rating, setRating] = useState(5);
  const [comment, setComment] = useState("");
  const feedback = trpc.journal.publicFeedback.useQuery(undefined, { enabled: isAuthenticated });
  const moderation = trpc.journal.moderationFeedback.useQuery(undefined, { enabled: isAuthenticated && user?.role === "admin" });
  const submit = trpc.journal.submitFeedback.useMutation({ onSuccess: () => { setComment(""); utils.journal.publicFeedback.invalidate(); } });
  const moderate = trpc.journal.moderateFeedback.useMutation({ onSuccess: () => { utils.journal.moderationFeedback.invalidate(); utils.journal.publicFeedback.invalidate(); } });
  const canSubmit = comment.trim().length >= 8 && !submit.isPending;

  return <div className="mx-auto max-w-7xl pb-12"><section className="overflow-hidden rounded-2xl border border-[#dba71d]/40 bg-[radial-gradient(circle_at_88%_12%,rgba(219,167,29,.2),transparent_28%),linear-gradient(145deg,#16170f,#0e100c_72%)] px-6 py-8 md:px-9 md:py-10"><div className="flex items-center gap-2 text-[#e2b540]"><MessageSquareHeart className="h-4 w-4" /><span className="text-[11px] font-bold uppercase tracking-[.17em]">Bashfx VIP Gold Room / Genuine member feedback</span></div><h1 className="mt-3 font-display text-5xl tracking-wide text-white md:text-6xl">COMMUNITY FEEDBACK</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#b7b4a8]">Share your honest experience with the journal. Feedback is submitted by signed-in members and appears here only after owner approval.</p></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="metal-border rounded-2xl bg-[#12130e] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#dba71d]/12 text-[#e2b43e]"><MessageSquareHeart className="h-5 w-5" /></div><h2 className="mt-5 font-display text-3xl tracking-wide text-white">LEAVE FEEDBACK</h2><p className="mt-2 text-sm leading-6 text-[#aaa79a]">Your review will be clearly identified as user-submitted. It is not published until it is reviewed.</p><div className="mt-5 flex gap-1" aria-label="Your rating">{[1, 2, 3, 4, 5].map(value => <button key={value} onClick={() => setRating(value)} className="rounded p-1 text-[#dba71d] hover:bg-[#dba71d]/10" aria-label={`${value} star rating`}><Star className={`h-6 w-6 ${value <= rating ? "fill-current" : ""}`} /></button>)}</div><Textarea value={comment} onChange={event => setComment(event.target.value)} placeholder="What has been useful about the journal?" className="mt-4 min-h-32 border-[#403a20] bg-[#090a07] text-sm text-white placeholder:text-[#5e5b51] focus:border-[#dba71d]" /><p className="mt-2 text-right text-[10px] text-[#878476]">{comment.length}/1000 · minimum 8 characters</p>{submit.isSuccess && <p className="mt-3 flex gap-2 text-xs text-[#98d68b]"><CheckCircle2 className="h-4 w-4" />Thank you. Your feedback is awaiting review.</p>}{submit.error && <p className="mt-3 rounded-lg border border-[#7f3932] bg-[#351612] p-3 text-xs leading-5 text-[#f38b80]">{submit.error.message}</p>}<Button disabled={!isAuthenticated || !canSubmit} onClick={() => submit.mutate({ rating, comment: comment.trim() })} className="mt-5 h-11 w-full bg-[#dba71d] font-bold text-[#170f03] hover:bg-[#f3ce66] disabled:opacity-50"><Send className="mr-2 h-4 w-4" />Submit genuine feedback</Button>{!isAuthenticated && <p className="mt-3 text-center text-xs text-[#e6be4a]">Sign in to submit your genuine feedback.</p>}</div>
      <div className="metal-border rounded-2xl bg-[#10110c] p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#dcb33f]">Approved member feedback</p><h2 className="mt-1 font-display text-3xl tracking-wide text-white">WHAT TRADERS SAY</h2></div><span className="rounded-full border border-[#4f4824] px-3 py-1 text-xs font-bold text-[#d4c37b]">{feedback.data?.length ?? 0} reviews</span></div>{feedback.isLoading ? <p className="py-14 text-center text-sm text-[#9f9b8d]">Loading approved feedback…</p> : feedback.error ? <p className="mt-5 rounded-lg border border-[#7f3932] bg-[#351612] p-3 text-xs leading-5 text-[#f38b80]">{feedback.error.message}</p> : feedback.data?.length ? <div className="mt-5 grid gap-4">{feedback.data.map(item => <article key={item.id} className="rounded-xl border border-[#3c381f] bg-[#0b0c09] p-5"><div className="flex items-center justify-between gap-3"><p className="font-semibold text-[#f4d36f]">{item.traderDisplayName || item.accountName || "Bashfx member"}</p><div className="flex text-[#e0b83f]">{Array.from({ length: item.rating }).map((_, index) => <Star key={index} className="h-3.5 w-3.5 fill-current" />)}</div></div><p className="mt-3 text-sm leading-6 text-[#c2bfb4]">{item.comment}</p><p className="mt-3 text-[10px] uppercase tracking-[.12em] text-[#777468]">Published {new Date(item.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}</p></article>)}</div> : <div className="flex min-h-72 flex-col items-center justify-center text-center"><MessageSquareHeart className="h-10 w-10 text-[#dba71d]/55" /><h3 className="mt-5 font-display text-3xl tracking-wide text-white">NO APPROVED FEEDBACK YET</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#9e9a8f]">Be the first member to send a genuine review after using the journal.</p></div>}</div></section>
    {user?.role === "admin" && <section className="metal-border mt-7 rounded-2xl bg-[#12130e] p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-[#e5bd49]" /><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#dcb33f]">Owner moderation</p><h2 className="font-display text-3xl tracking-wide text-white">REVIEW QUEUE</h2></div></div><div className="mt-5 space-y-3">{moderation.data?.filter(item => item.status === "pending").map(item => <div key={item.id} className="flex flex-col justify-between gap-3 rounded-xl border border-[#403a20] bg-[#0b0c09] p-4 md:flex-row md:items-center"><div><p className="text-sm font-semibold text-[#e9c459]">{item.traderDisplayName || item.accountName || "Bashfx member"} · {item.rating}/5</p><p className="mt-1 text-sm text-[#c2bfb4]">{item.comment}</p></div><div className="flex shrink-0 gap-2"><Button size="sm" onClick={() => moderate.mutate({ feedbackId: item.id, status: "approved" })} className="bg-[#3e7d35] text-white hover:bg-[#529844]">Approve</Button><Button size="sm" variant="outline" onClick={() => moderate.mutate({ feedbackId: item.id, status: "hidden" })} className="border-[#7b3933] text-[#f18a80] hover:bg-[#3b1715] hover:text-[#ffb2ab]">Hide</Button></div></div>)}{!moderation.data?.some(item => item.status === "pending") && <p className="py-5 text-sm text-[#99968a]">No feedback awaits moderation.</p>}</div></section>}</div>;
}
