import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CalendarRange, Download, ImageIcon, Loader2, LockKeyhole, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";

export default function MonthlySummary() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const { data: summaries } = trpc.journal.monthlySummaries.useQuery(undefined, { enabled: isAuthenticated });
  const { data: automation } = trpc.journal.monthlyAutomationStatus.useQuery(undefined, { enabled: isAuthenticated });
  const [summaryId, setSummaryId] = useState<number | null>(null);
  const asset = trpc.journal.monthlySummaryAsset.useQuery({ summaryId: summaryId ?? 0 }, { enabled: Boolean(summaryId) });
  const generate = trpc.journal.generateMonthlySummary.useMutation({ onSuccess: ({ summaryId: nextId }) => { setSummaryId(nextId); utils.journal.monthlySummaries.invalidate(); } });
  const enableAutomation = trpc.journal.enableMonthlyAutomation.useMutation({ onSuccess: () => utils.journal.monthlyAutomationStatus.invalidate() });

  useEffect(() => { if (!summaryId && summaries?.[0]) setSummaryId(summaries[0].id); }, [summaries, summaryId]);

  return <div className="mx-auto max-w-7xl pb-12"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#ddb437]">Bashfx VIP Gold Room / Full calendar month</p><h1 className="mt-2 font-display text-5xl tracking-wide text-white md:text-6xl">MONTHLY SUMMARY</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#aaa79a]">Review every saved market pair across a calendar month. Your chosen Trader Name, net pips, and News Trade labels are carried into the premium result image.</p></div><div className="rounded-xl border border-[#554920] bg-[#15150e] px-4 py-3 text-xs text-[#c4c0b3]"><span className="font-bold text-[#f0c95e]">Automatic month-end:</span> {automation?.enabled ? "active" : "ready to enable"}</div></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="metal-border rounded-2xl bg-[#12130e] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#dba71d]/12 text-[#e2b43e]"><CalendarRange className="h-5 w-5" /></div><h2 className="mt-5 font-display text-3xl tracking-wide text-white">MONTH IN REVIEW</h2><p className="mt-3 text-sm leading-6 text-[#aaa79a]">Generate the current month whenever you are ready. At month-end, the automatic workflow creates the closed month’s image and sends a private readiness notice.</p>{generate.error && <p className="mt-5 rounded-lg border border-[#7f3932] bg-[#351612] p-3 text-xs leading-5 text-[#f38b80]">{generate.error.message}</p>}<Button disabled={!isAuthenticated || generate.isPending} onClick={() => generate.mutate()} className="mt-7 h-12 w-full bg-[#dba71d] font-bold text-[#170f03] hover:bg-[#f3ce66] disabled:opacity-50">{generate.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Rendering monthly image…</> : <><Sparkles className="mr-2 h-4 w-4" />Generate current month</>}</Button>{automation?.canManage && !automation.enabled && <Button disabled={enableAutomation.isPending} variant="outline" onClick={() => enableAutomation.mutate()} className="mt-3 h-10 w-full border-[#705d25] bg-transparent text-[#eaca61] hover:bg-[#dba71d]/10 hover:text-[#ffe9a6]">{enableAutomation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <LockKeyhole className="mr-2 h-4 w-4" />}Enable automatic month-end summary</Button>}<p className="mt-4 text-xs leading-5 text-[#918e82]">{automation?.schedule}</p></div>
      <div className="metal-border min-h-[560px] overflow-hidden rounded-2xl bg-[#10110c] p-4 md:p-6"><div className="mb-4 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><ImageIcon className="h-4 w-4 text-[#e2b43e]" /><span className="text-xs font-bold uppercase tracking-[.14em] text-[#b3ae9d]">Monthly result image</span></div>{asset.data?.url && <a href={asset.data.url} download={`bashfx-monthly-summary-${asset.data.monthKey}.png`} target="_blank" rel="noreferrer"><Button size="sm" className="h-8 bg-[#dba71d] px-3 text-xs font-bold text-[#170f03] hover:bg-[#f3ce66]"><Download className="mr-1.5 h-3.5 w-3.5" />Download PNG</Button></a>}</div>{asset.isLoading ? <div className="flex h-[480px] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#dba71d]" /></div> : asset.data?.url ? <div className="flex justify-center rounded-xl border border-[#3e391f] bg-[#080906] p-3"><img src={asset.data.url} alt="Generated Bashfx monthly trading summary" className="max-h-[620px] rounded-md object-contain shadow-[0_18px_55px_rgba(0,0,0,.55)]" /></div> : <div className="flex h-[480px] flex-col items-center justify-center rounded-xl border border-dashed border-[#4a421e] bg-[#0b0c09] px-8 text-center"><CalendarRange className="h-10 w-10 text-[#dba71d]/65" /><h3 className="mt-5 font-display text-3xl tracking-wide text-white">YOUR MONTHLY IMAGE WILL APPEAR HERE</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#9e9a8f]">Add trades throughout the month, then generate your full review—or let the scheduled month-end workflow create it.</p></div>}</div></section>
    {summaries && summaries.length > 0 && <section className="mt-7"><p className="mb-3 text-[11px] font-bold uppercase tracking-[.16em] text-[#948e79]">Monthly history</p><div className="flex flex-wrap gap-2">{summaries.map(summary => <Button key={summary.id} variant="outline" onClick={() => setSummaryId(summary.id)} className={`border-[#4a421e] bg-[#12130e] text-xs ${summaryId === summary.id ? "text-[#f3cb58]" : "text-[#aca99c]"}`}>{summary.monthKey}</Button>)}</div></section>}</div>;
}
