import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Download, ImageIcon, Loader2, Sparkles, WandSparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";

export default function WeeklySummary() {
  const { isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const { data: dashboard } = trpc.journal.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const { data: summaries } = trpc.journal.summaries.useQuery(undefined, { enabled: isAuthenticated });
  const [summaryId, setSummaryId] = useState<number | null>(null);
  const asset = trpc.journal.summaryAsset.useQuery({ summaryId: summaryId ?? 0 }, { enabled: Boolean(summaryId) });
  const generate = trpc.journal.generateWeeklySummary.useMutation({ onSuccess: ({ summaryId: newId }) => { setSummaryId(newId); utils.journal.summaries.invalidate(); } });
  useEffect(() => { if (!summaryId && summaries?.[0]) setSummaryId(summaries[0].id); }, [summaries, summaryId]);
  const metrics = dashboard?.metrics;
  const canGenerate = Boolean(metrics?.totalTrades);
  return <div className="mx-auto max-w-7xl pb-10"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.16em] text-[#ddb437]">BashFX creative studio</p><h1 className="mt-2 font-display text-5xl tracking-wide text-white">WEEKLY SUMMARY</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#aaa79a]">Turn this week’s verified journal entries into a premium BashFX result graphic. The visual model uses your reference layout and the live data in your trade log.</p></div><Link href="/trades"><Button variant="outline" className="border-[#dba71d]/55 bg-transparent text-[#e9c24d] hover:bg-[#dba71d]/10 hover:text-[#ffe49a]">Check trades first</Button></Link></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><div className="metal-border rounded-2xl bg-[#12130e] p-6"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#dba71d]/12 text-[#e2b43e]"><WandSparkles className="h-5 w-5" /></div><h2 className="mt-5 font-display text-3xl tracking-wide text-white">CREATE THIS WEEK’S REPORT</h2><p className="mt-3 text-sm leading-6 text-[#aaa79a]">The generator reads saved trade values—pair, direction, pips, result, and weekly metrics—and applies the BashFX gold-and-black summary composition.</p><div className="my-6 h-px bg-[#4a421e]" /><div className="grid grid-cols-2 gap-3 text-sm"><Stat label="Trades" value={String(metrics?.totalTrades ?? 0)} /><Stat label="Win rate" value={`${metrics?.winRate ?? 0}%`} /><Stat label="Net pips" value={`${(metrics?.totalPips ?? 0) > 0 ? "+" : ""}${metrics?.totalPips ?? 0}`} /><Stat label="Wins / losses" value={`${metrics?.wins ?? 0} / ${metrics?.losses ?? 0}`} /></div>{generate.error && <p className="mt-5 rounded-lg border border-[#7f3932] bg-[#351612] p-3 text-xs leading-5 text-[#f38b80]">{generate.error.message}</p>}<Button disabled={!isAuthenticated || !canGenerate || generate.isPending} onClick={() => generate.mutate()} className="mt-7 h-12 w-full bg-[#dba71d] font-bold text-[#170f03] hover:bg-[#f3ce66] disabled:opacity-50">{generate.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Rendering your summary…</> : <><Sparkles className="mr-2 h-4 w-4" />Generate BashFX summary</>}</Button>{!canGenerate && <p className="mt-3 text-center text-xs text-[#e2bd59]">Add and verify at least one trade to unlock generation.</p>}</div>
      <div className="metal-border min-h-[570px] overflow-hidden rounded-2xl bg-[#10110c] p-4 md:p-6"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><ImageIcon className="h-4 w-4 text-[#e2b43e]" /><span className="text-xs font-bold uppercase tracking-[0.14em] text-[#b3ae9d]">Rendered output</span></div>{asset.data?.url && <a href={asset.data.url} download={`bashfx-weekly-summary-${new Date().toISOString().slice(0, 10)}.png`} target="_blank" rel="noreferrer"><Button size="sm" className="h-8 bg-[#dba71d] px-3 text-xs font-bold text-[#170f03] hover:bg-[#f3ce66]"><Download className="mr-1.5 h-3.5 w-3.5" />Download PNG</Button></a>}</div>{asset.isLoading ? <div className="flex h-[500px] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#dba71d]" /></div> : asset.data?.url ? <div className="flex justify-center rounded-xl border border-[#3e391f] bg-[#080906] p-3"><img src={asset.data.url} alt="Generated BashFX weekly Forex summary" className="max-h-[620px] rounded-md object-contain shadow-[0_18px_55px_rgba(0,0,0,.55)]" /></div> : <div className="flex h-[500px] flex-col items-center justify-center rounded-xl border border-dashed border-[#4a421e] bg-[#0b0c09] px-8 text-center"><ImageIcon className="h-10 w-10 text-[#dba71d]/65" /><h3 className="mt-5 font-display text-3xl tracking-wide text-white">YOUR IMAGE WILL APPEAR HERE</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#9e9a8f]">Once generated, you can inspect the output and download the PNG from this panel.</p></div>}</div></section>
    {summaries && summaries.length > 0 && <section className="mt-7"><p className="mb-3 text-[11px] font-bold uppercase tracking-[0.16em] text-[#948e79]">Summary history</p><div className="flex flex-wrap gap-2">{summaries.map(summary => <Button key={summary.id} variant="outline" onClick={() => setSummaryId(summary.id)} className={`border-[#4a421e] bg-[#12130e] text-xs ${summaryId === summary.id ? "text-[#f3cb58]" : "text-[#aca99c]"}`}>{new Date(summary.createdAt).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}</Button>)}</div></section>}</div>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-[#3d381f] bg-[#0c0d09] p-3"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-[#858277]">{label}</p><p className="mt-1 font-display text-2xl tracking-wide text-[#edca68]">{value}</p></div>; }
